language: python
python: 2.7
sudo: required
services:
  - docker
cache:
  pip: true
  directories:
    - $HOME/buildout-cache
env:
  - PLONE_VERSION=4.3.x
  - PLONE_VERSION=5.0.x
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - virtualenv .
  - sudo apt install python2.7 python2.7-dev
  - bin/pip install -r requirements.txt
install:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
script:
  - bin/code-analysis
  - bin/test
  - bin/test-no-uncommitted-doc-changes
after_success:
  - bin/test-coverage
  - bin/createcoverage
  - pip install coverage==3.7.1 coveralls
  - coveralls
  - docker.io build --tag plone.restapi:$(git rev-parse HEAD) .
#  - docker.io push plone/plone.restapi
